version: '2.3'

# create default network
networks:
  default:
    name: ros-network

volumes:
  workspace:

services:

  workspace:
    build: ./image
    image: wn1980/ros1-noetic${TAG}
    container_name: ros1_noetic
    init: true
    restart: unless-stopped
    privileged: true
    #depends_on: 
    #  - master
    environment:
      - DISPLAY=:1
      - ROS_MASTER_URI=http://master:11311
      #- QT_X11_NO_MITSHM=1
      #- TURTLEBOT_3D_SENSOR=asus_xtion_pro
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20
    ports:
      - "8558:8558"
      - "9903:9901"